In [3]:
import numpy as np
a= np.array([1,2,3])
print (a)

[1 2 3]


In [4]:
# more than one dimensions
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [5]:
#minimum dimensions
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [6]:
#dtype parameter 
a=np.array([1,2,3],dtype=complex)
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
import numpy
numpy.array

<function numpy.core.multiarray.array>

In [12]:
# numpy- Data types
#using array-scalar type
import numpy as np
dt=np.dtype(np.int64)
print(dt)

int64


In [13]:
#int8,int 16,int 32,int 64 can be replaced by equivalent string 'i1','i2','i4',etc 
import numpy as np
dt=np.dtype('i4')
print(dt)

int32


In [19]:
# an example
import numpy as np 
a =np.arange(15).reshape(3,5)
a
a.shape
a.ndim
a

2